language: python

sudo: required

services:
 - docker

before_install:
 - docker pull mysql:5.7.14
 - mkdir db
 - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v db:/var/lib/mysql  mysql:5.7.14
 - ls -la
 - pwd
 - docker run -it --name mysql-cmdline -v ~/travis/CS4501-EMS/mysql_shell:/home --link mysql:db mysql:5.7.14 bash -c "chmod +x /home/mysql.sh && /home/mysql.sh"
 - docker-compose up -d
 - docker exec -it cs4501ems_models_1 bash -c "python manage.py test"
 