models:
    image: tp33/django
    external_links:
      -  project_mysql:db
    volumes:
      - ~/cs4501/CS4501-EMS/app:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory CS4501-EMS/app --reload-on-changes CS4501-EMS/app/tech_consult/tech_consult/wsgi.py"
