# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-14 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=200, unique=True)),
                ('password', models.CharField(default='none', max_length=200)),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
                ('phone', models.CharField(default='none', max_length=200)),
                ('email', models.EmailField(default='none', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
                ('offered_price', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('availability', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=200, unique=True)),
                ('password', models.CharField(default='none', max_length=200)),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
                ('phone', models.CharField(default='none', max_length=200)),
                ('email', models.EmailField(default='none', max_length=200)),
                ('bio', models.CharField(default='none', max_length=250)),
                ('skills', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('author', models.CharField(default='none', max_length=50)),
                ('comment', models.CharField(default='none', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Review'),
        ),
        migrations.AddField(
            model_name='producer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='accepted_producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Producer'),
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Consumer'),
        ),
    ]
