# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-14 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='user',
        ),
    ]
