# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180301_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('authenticator', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('is_consumer', models.BooleanField(default=True)),
                ('date_created', models.CharField(max_length=50)),
            ],
        ),
    ]
