# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_authenticator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='password',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='producer',
            name='password',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
